#
# Copyright (c) 2022 Darryl deHaan
# SPDX-License-Identifier: MIT
#

# 3 profiles (n+2)
CONFIG_BT_MAX_CONN=6
CONFIG_BT_MAX_PAIRED=6

# dongle mode
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

CONFIG_BT_BAS=n
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
