CONFIG_BT_DEVICE_NAME="AnyWhy Flake BT"

CONFIG_PM_DEVICE=y
CONFIG_ZMK_SLEEP=y
# 30 minutes sleep
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000
CONFIG_ZMK_PM_SOFT_OFF=y

# Enables a combination of settings that are planned to be default in future
# versions of ZMK to improve connection stability. This includes changes to
# timing on BLE pairing initiation, restores use of the updated/new LLCP
# implementation, and disables 2M PHY support.
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=n
CONFIG_ZMK_STUDIO_LOCKING=n
# Max TX power for reliable BLE to both peripherals + host
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Report battery peripheral battery level
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# Report type NKRO enabled
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y

# Debouncing
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=8
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=8
